[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "LibRVC"
version = "0.0.1"
dynamic = ["dependencies"]

[tool.setuptools.package-data]
librvc = ["**/*.json"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}